name: acupcakeshop-portal
services:
  - name: acupcakeshop
    github:
      branch: main
      repo: aspenas/acupcakeshop-portal
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    environment_slug: node-js
    build_command: npm install
    run_command: npm start
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: PORT
        value: 3000
        scope: RUN_AND_BUILD_TIME
      - key: OBSIDIAN_VAULT_PATH
        value: ./
        scope: RUN_AND_BUILD_TIME 